# command_constants.py
# import this to have all the constants needed to reference commands.

FORWARD_HEADER = 0xCA
FORWARD_FOOTER = 0x47
RETURN_HEADER = 0xAC
RETURN_FOOTER = 0x74

NUM_MOTORS = 5

COMMAND_TEST = 0x00
COMMAND_HALT = 0x0F
COMMAND_SET_MOTOR_MICROSECONDS = 0x10
COMMAND_SET_MOTOR_CALIBRATED = 0x12
COMMAND_SET_MOTOR_CALIBRATION = 0x13
COMMAND_GET_IMU = 0x30
COMMAND_SET_ACCEL_SETTINGS = 0x33
COMMAND_SET_GYRO_SETTINGS = 0x34
COMMAND_GET_IMU_SETTINGS = 0x35
COMMAND_GET_VOLT_TEMP = 0x40
COMMAND_SET_VOLTAGE_CALIBRATION = 0x43
COMMAND_SET_AUTOREPORT = 0x50
COMMAND_SET_FEEDBACK = 0x51

AXIS_DIVISOR = 0x30

RETURN_TEST = 0x00
RETURN_OK = 0x0A
RETURN_MOTOR = 0x1C
RETURN_ACCELEROMETER = 0x3A
RETURN_GYROSCOPE = 0x3C
RETURN_LINEAR_ACCEL = 0x3B
RETURN_ORIENTATION = 0x3D
RETURN_IMU_CALIBRATIONS = 0x3E
RETURN_VOLT_TEMP = 0x44

PARAM_ZERO = 0x00
PARAM_SYSTEM = 0x01
PARAM_ACCEL = 0x15
PARAM_GYRO = 0x16
PARAM_VOLT_TEMP = 0x17
PARAM_LINEAR_ACCEL = 0x18
PARAM_ORIENTATION = 0x19
PARAM_TEST_SYSTEM = 0xF0

MOTOR_CLAW = 4
MOTOR_FRONT = 0
MOTOR_RIGHT = 3
MOTOR_LEFT = 2
MOTOR_BACK = 1
